//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
        [Required(ErrorMessage = "UserName Không Được Trống")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "UserName Phải Chứa Ít Nhất 3 Ký Tự")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Số Điện Thoại Không Được Trống")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$", ErrorMessage = "Vui Lòng Kiểm Tra Lại Số Điện Thoại Bắt Đầu = +84")]
        public string UserPhone { get; set; }

        [Required(ErrorMessage = "Tên Không Được Trống")]
        public string NameUser { get; set; }

        [Required(ErrorMessage = "Email Không Được Trống")]
        [DataType(DataType.EmailAddress)]
        public string UserEmail { get; set; }

        [MaxLength(100, ErrorMessage = "Mật Khẩu Không Được Quá 100 Kí Tự")]
        public string UserPassword { get; set; }
        public int RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
    }
}
